sudo: false
dist: trusty
language: ruby
rvm:
  - '2.5.3'
  - '2.4.1'
  - '2.3.4'
  - '2.2.7'
  - '2.1.10'
env:
  - GEM=will_paginate
  - GEM=kaminari
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_head.gemfile
matrix:
  exclude:
    - rvm: '2.1.10'
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: '2.1.10'
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: '2.1.10'
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: '2.1.10'
      gemfile: gemfiles/rails_head.gemfile
  allow_failures:
  - gemfile: gemfiles/rails_head.gemfile
